// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCikohP12Nz91Q2JADLu9YmF4CtQFsiMAc',
    appId: '1:319004756606:web:0e989e154257b20bf9662f',
    messagingSenderId: '319004756606',
    projectId: 'flutter-puzzle-hack-e2f1a',
    authDomain: 'flutter-puzzle-hack-e2f1a.firebaseapp.com',
    storageBucket: 'flutter-puzzle-hack-e2f1a.appspot.com',
    measurementId: 'G-GCY9S3V29Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbY-DFNZhavtV3yt-3ioOrHnZWqegS1ME',
    appId: '1:319004756606:android:b8d2c62c1d34f7f0f9662f',
    messagingSenderId: '319004756606',
    projectId: 'flutter-puzzle-hack-e2f1a',
    storageBucket: 'flutter-puzzle-hack-e2f1a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTkG1DKIu80LWotr7W8u6Mvs76HFWI0Ac',
    appId: '1:319004756606:ios:5f579d419de7e768f9662f',
    messagingSenderId: '319004756606',
    projectId: 'flutter-puzzle-hack-e2f1a',
    storageBucket: 'flutter-puzzle-hack-e2f1a.appspot.com',
    iosClientId: '319004756606-7e3nvoi5qgpq0h334fum9e2p96vn4v81.apps.googleusercontent.com',
    iosBundleId: 'com.mullr.puzzle',
  );
}
